#
# Ansible to provision HashiCorp Vault on remote host
#
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Gather facts
      setup:
  roles:
    - ehime.vault
